name: Lab 4 CI Pipeline
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js 24.x
          uses: actions/setup-node@v4
          with:
            node-version: "24"
        - name: Install dependencies
          run: npm clean-install
        - name: Run linter
          run: npm run lint

unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: "24"
    - name: Install dependencies
      run: npm clean-install
    - name: Run unit tests
      run: npm run test-unit
    - if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-${{ github.sha }}
        path: reports/report.xml